# Generated by Django 5.1.4 on 2024-12-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paintai", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="isactivate",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="camera",
            name="isdeleted",
            field=models.BooleanField(default=False),
        ),
    ]
