# Generated by Django 5.1.4 on 2024-12-05 12:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paintai", "0002_camera_isactivate_alter_camera_isdeleted"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("isdeleted", models.BooleanField(default=False)),
                ("createdon", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
