# Generated by Django 5.1.4 on 2024-12-05 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paintai", "0003_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="yoloid",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="ProductProduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("starttime", models.DateTimeField()),
                ("endtime", models.DateTimeField()),
                (
                    "cameraid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="paintai.camera"
                    ),
                ),
                (
                    "productid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="paintai.product",
                    ),
                ),
            ],
        ),
    ]
