# Generated by Django 5.1.4 on 2024-12-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paintai", "0004_product_yoloid_productproduction"),
    ]

    operations = [
        migrations.AddField(
            model_name="productproduction",
            name="count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
